[[pages]]
path = "app.py"
name = "ë©”ì¸ ëŒ€ì‹œë³´ë“œ"
icon = "ğŸš—"

[[pages]]
path = "money.py"
name = "ë³´ì¡°ê¸ˆ ì •ë³´"
icon = "ğŸ’°"

[[pages]]
path = "pages/FAQ.py"
name = "ê¸°ì—… FAQ"
icon = "â“" 